# Generated by Django 4.2.1 on 2023-05-09 05:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employee_management', '0002_alter_person_email_alter_person_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
                ('name', models.CharField(max_length=256)),
                ('email', models.CharField(max_length=1024)),
                ('phone', models.CharField(max_length=10)),
                ('desgination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee_management.designation')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
