# Generated by Django 4.2.1 on 2023-05-09 07:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee_management', '0005_alter_person_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='desgination',
            new_name='designation',
        ),
    ]
