# Generated by Django 4.2.1 on 2023-05-09 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_management', '0006_rename_desgination_employee_designation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='email',
            field=models.CharField(max_length=1024, unique=True),
        ),
    ]
